import { createContext } from 'react'
import { TColor, WHITE, BLACK } from '../../colors'

export type TCheckmarkThemeContext = {
  backgroundColor: TColor,
  activeBackgroundColor: TColor,
  hoveredBackgroundColor: TColor,
  activeHoveredBackgroundColor: TColor,
  pressedBackgroundColor: TColor,
  activePressedBackgroundColor: TColor,
  disabledBackgroundColor: TColor,
  activeDisabledBackgroundColor: TColor,
  borderColor: TColor,
  activeBorderColor: TColor,
  hoveredBorderColor: TColor,
  activeHoveredBorderColor: TColor,
  pressedBorderColor: TColor,
  activePressedBorderColor: TColor,
  disabledBorderColor: TColor,
  activeDisabledBorderColor: TColor,
  focusedOuterBorderColor: TColor,
  activeFocusedOuterBorderColor: TColor,
  iconColor: TColor,
  hoveredIconColor: TColor,
  pressedIconColor: TColor,
  disabledIconColor: TColor,
}

export const CheckmarkThemeContext = createContext<TCheckmarkThemeContext>({
  backgroundColor: WHITE,
  activeBackgroundColor: WHITE,
  hoveredBackgroundColor: WHITE,
  activeHoveredBackgroundColor: WHITE,
  pressedBackgroundColor: WHITE,
  activePressedBackgroundColor: WHITE,
  disabledBackgroundColor: WHITE,
  activeDisabledBackgroundColor: WHITE,
  borderColor: WHITE,
  hoveredBorderColor: WHITE,
  activeBorderColor: WHITE,
  activeHoveredBorderColor: WHITE,
  pressedBorderColor: WHITE,
  activePressedBorderColor: WHITE,
  disabledBorderColor: WHITE,
  activeDisabledBorderColor: WHITE,
  activeFocusedOuterBorderColor: WHITE,
  focusedOuterBorderColor: WHITE,
  iconColor: BLACK,
  hoveredIconColor: BLACK,
  pressedIconColor: BLACK,
  disabledIconColor: BLACK,
})
