export const CANVAS_PADDING = 80
export const CONTROLS_HEIGHT_BOTTOM = 94
export const CONTROLS_HEIGHT_TOP = 94
export const PAGE_BACKGROUND = '#1e2730'
export const PATH_WIDTH = 8
export const POINT_BORDER = 6
export const POINT_RADIUS = 6
export const TOOLTIP_FONT_SIZE = 16
export const BUTTON_FONT_SIZE = 14
export const TOOLTIP_PADDING = 4
export const TOOLTIP_X_OFFSET = 12
export const TOOLTIP_Y_OFFSET = 12
export const GRAPH_OFFSET = POINT_RADIUS + POINT_BORDER / 2
