exports.plugins = [
  require('remark-lint'),
  [require('remark-lint-blockquote-indentation'), 2],
  [require('remark-lint-checkbox-character-style'), { checked: 'x', unchecked: ' ' }],
  require('remark-lint-checkbox-content-indent'),
  [require('remark-lint-code-block-style'), 'fenced'],
  require('remark-lint-definition-case'),
  require('remark-lint-definition-spacing'),
  [require('remark-lint-emphasis-marker'), '_'],
  [require('remark-lint-fenced-code-flag'), { allowEmpty: true, flags: ['ts', 'js', 'json', 'sh'] }],
  [require('remark-lint-fenced-code-marker'), '`'],
  require('remark-lint-final-definition'),
  require('remark-lint-final-newline'),
  [require('remark-lint-first-heading-level'), 1],
  require('remark-lint-hard-break-spaces'),
  require('remark-lint-heading-increment'),
  [require('remark-lint-heading-style', 'atx')],
  [require('remark-lint-link-title-style'), '"'],
  require('remark-lint-list-item-bullet-indent'),
  require('remark-lint-list-item-content-indent'),
  [require('remark-lint-list-item-indent'), 'space'],
]
